### ISSUE TITLE
Unable to install python bindings in Docker container

### ISSUE THREAD

**Issue by abhishekkrthakur** [facebookresearch/flashlight#462]
I tried my best to install the python bindings in docker container but for some reason it always fails.

Here is the log:

```
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/lib/x86_64-linux-gnu/liblzma.so (found version "5.2.4")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- kenlm library not found; if you already have kenlm installed, please set CMAKE_LIBRARY_PATH, KENLM_LIB or KENLM_ROOT environment variable
-- kenlm utils library not found; if you already have kenlm installed, please set CMAKE_LIBRARY_PATH, KENLM_UTIL_LIB or KENLM_ROOT environment variable
-- kenlm model.hh found in /opt/kenlm/include/kenlm/lm
-- Found kenlm: /opt/kenlm/include
-- Found kenlm (include: /opt/kenlm/include, library: KENLM_LIB-NOTFOUND;KENLM_UTIL_LIB-NOTFOUND;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
KENLM_LIB
    linked by target "fl-libraries" in directory /flashlight
KENLM_UTIL_LIB
    linked by target "fl-libraries" in directory /flashlight

-- Configuring incomplete, errors occurred!
See also "/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

And here is the Dockerfile:

```
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive
ENV CUDACXX=/usr/local/cuda/bin/nvcc
ENV CMAKE_PREFIX_PATH=/usr/include/mkl/:$PATH
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/lib/x86_64-linux-gnu/libcuda.so.1

RUN apt update && apt install -y \
    wget \
    build-essential \
    git \
    cmake \
    make \
    gcc \
    g++ \
    libboost-all-dev \
    libasound2-dev \
    libopenmpi-dev \
    gnupg2 \
    python3-pip \
    intel-mkl-full \
    liblzma-dev \
    libbz2-dev \
    libgoogle-glog-dev \
    libtool \
    libvorbis-dev \
    libogg-dev \
    libflac-dev \
    libfftw3-dev

# install requirements.txt
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

RUN wget https://arrayfire.s3.amazonaws.com/3.8.0/ArrayFire-v3.8.0_Linux_x86_64.sh
RUN sh ArrayFire-v3.8.0_Linux_x86_64.sh --include-subdir --prefix=/opt

# install kenlm
RUN git clone https://github.com/kpu/kenlm.git && \
    cd kenlm && git checkout 0c4dd4e && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/opt/kenlm \
             -DCMAKE_POSITION_INDEPENDENT_CODE=ON && \
    make install -j12 && \
    cd .. && python3 setup.py install

ENV KENLM_ROOT_DIR=/opt/kenlm/include
# install flashlight
RUN git clone --recursive https://github.com/facebookresearch/flashlight.git && \
    cd flashlight && git checkout 68317bd8932d0e7583d102e5db0ca8146199f74e && \
    mkdir -p build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/opt/flashlight \
             -DFL_BACKEND=CUDA \
             -DArrayFire_DIR=/opt/arrayfire \
             -DKENLM_ROOT=/opt/kenlm \
             -DFL_LIBRARIES_BUILD_FOR_PYTHON="ON" \
             -DPYBIND11_PYTHON_VERSION="3.8" \
             -DCMAKE_POSITION_INDEPENDENT_CODE="ON" && \
    make install -j12
RUN cd flashlight/bindings/python && pip3 install .

# install torch for cuda 11
RUN pip3 install --pre torch torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U

# install fairseq
RUN git clone https://github.com/pytorch/fairseq.git && \
    cd fairseq && \
    git checkout v0.10.2 && pip3 install .
```

Any help is appreciated. :)

**Comment by tlikhomanenko** [comment]
Please use `KENLM_ROOT` instead of `KENLM_ROOT_DIR`.

**Comment by abhishekkrthakur** [comment]
Realized it sometime after posting this issue and thus closed it :) Thank you for the help :)

**Comment by PeiyuChen1005** [comment]
So what's the solution to this question? I've tried to add `export KENLM_ROOT=/path/to/kenlm/include` to my `~/.bashrc ` file(I'm not a root user) but still get the same problem.

**Comment by tlikhomanenko** [comment]
It should be export KENLM_ROOT=/path/to/kenlm/ also make sure that you didd source on bashrc before building fl
