### ISSUE TITLE
issue while installing flashlight python bindings

### ISSUE THREAD

**Issue by roboticsai** [facebookresearch/flashlight#515]
The issue is:
```
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /usr/local/lib/libkenlm.a
-- Using kenlm utils library found in /usr/local/lib/libkenlm_util.a
-- kenlm model.hh found in /usr/local/include/kenlm/lm
-- Found kenlm (include: /usr/local/include, library: /usr/local/lib/libkenlm.a;/usr/local/lib/libkenlm_util.a;/home/robot/anaconda3/envs/fairseq/lib/liblzma.so;/home/robot/anaconda3/envs/fairseq/lib/libbz2.so;/home/robot/anaconda3/envs/fairseq/lib/libz.so)
-- Found PythonInterp: /home/robot/anaconda3/envs/fairseq/bin/python (found version "3.6.13") 
-- Found PythonLibs: /home/robot/anaconda3/envs/fairseq/lib/libpython3.6m.so
-- Configuring incomplete, errors occurred!
See also "/home/robot/airobotics/speech/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/robot/airobotics/speech/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 135, in <module>
    python_requires=">=3.6",
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 107, in build_extensions
    ["cmake", source_dir] + cmake_args, cwd=self.build_temp, env=env
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/robot/airobotics/speech/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/robot/airobotics/speech/flashlight/bindings/python/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/robot/anaconda3/envs/fairseq/bin/python', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

```
Environment:
OS: Ubuntu 20.04 conda 4.9.2 env 
nvcc --version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```
fftw version: fftw-3.3.9

Issue recreation:
1. git clone https://github.com/facebookresearch/flashlight.git
2. cd flashlight/binding/python
3. python3 setup.py install

**Comment by tlikhomanenko** [comment]
Can you post the full log, in current log I don't see where cmake crashed for you.

**Comment by roboticsai** [comment]
I have now installed the flashlight python bindings in a docker environment and the issue is gone. Previously i was using conda environment where it was little complicated to install it.

**Comment by tlikhomanenko** [comment]
Closing then the issue. However I tested in clean conda, it is working for me. Maybe you have some other libs in your conda which are another version and this messed up bindings.
